wandb_version: 1

weight_decay:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.9
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.1
iterations:
  desc: null
  value: 64000
n:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1714090866.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 1
      - 2
      - 5
      13: darwin-x86_64
